# Task Worker constants

TASK_TYPE_GRADE_PAPER = "grade_paper"
TASK_STATUS_PENDING = "pending"
TASK_STATUS_PROCESSING = "processing"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"

WORKER_POLL_INTERVAL = 2
TASK_LOCK_TIMEOUT_MINUTES = 30
STRICT_EXAM_TIMEOUT_MINUTES = 10
