from .generic_responses import *
from .auth_responses import *
from .grading_responses import *
from .exam_responses import *
from .upload_responses import *
from .student_portal_responses import *
from .feedback_responses import *
from .analytics_responses import *
from .admin_responses import *
from .batch_responses import *
from .student_responses import *
from .submission_responses import *
from .misc_responses import *
